name = "CTProblems"
uuid = "45d9ea3f-a92f-411f-833f-222dd4fb9cd8"
authors = ["Olivier Cots <olivier.cots@enseeiht.fr>"]
version = "0.1.0"

[deps]
CTBase = "54762871-cc72-4466-b8e8-f6c8b58076cd"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
CTBase = "0.4"
Plots = "1.38"
julia = "1.8"
