name = "CTProblems"
uuid = "45d9ea3f-a92f-411f-833f-222dd4fb9cd8"
authors = ["Olivier Cots <olivier.cots@enseeiht.fr>"]
version = "0.1.4"

[deps]
CTBase = "54762871-cc72-4466-b8e8-f6c8b58076cd"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"

[compat]
CTBase = "0.5"
DocStringExtensions = "0.9"
julia = "1.8"